#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from .model import Model

class Link:
    def __init__(self, input, output, function=None):
        
        """
        Connect two Models

        Parameters
        ----------
        input : TYPE
            input model, providing data to the output model
        output : TYPE
            output model, receiving data generated by the input model
        func : TYPE, optional
            Function connecting variables (default None)

        """
        
        # initialize the properties
        self.__input = None
        self.__output = None
        self.__function = None
        
        # set the properties
        self.input, self.output, self.function = \
            input, output, function
        
        
    @property
    def input(self):
        """
        Returns
        -------
            input model of the link
        """
        return self.__input
    
    
    @input.setter
    def input(self, m):
        """
        Parameters
        ----------
        m : Model
            Model of input
        """
        assert isinstance(m, Model)
        self.__input =  m
        
        
    @property
    def output(self):        
        """
        Returns
        -------
        output model of the link
        """
        return self.__output
    
    
    @output.setter
    def output(self, m):
        """
        Parameters
        ----------
        m : Model
            Model of output
        """
        assert isinstance(m, Model)
        self.__output =  m
        
        
    @property
    def function(self):
        """
        Returns
        -------
           function elaborating connections
        """
        return self.__function
    
    
    @function.setter
    def function(self, func):
        """
        func : callable
               Function connecting input and output model
               It can be None or callable object
        """
        
        # if function is None don't do anything
        if func is None:
            self.__function = func
            return
        
        
        # it is a function
        assert (callable(func) and \
                func.__code__.co_varnames == (
                    "input", "output"
                    ))
            
        self.__function = func
        
        # execute the function
        self.__function(self.input, self.output)



        
          

if __name__ == "__main__":
    from model import Model
    m1 = Model("m1")
    m2 = Model("m2")
    l = Link(m1, m2)
    m1.test1 = 2
    m2.test2 = 44
    
    def myfunc(input, output):
        output.test2 = input.test1
        
    l.function = myfunc
        
    print (m1.test1, m2.test2)
